apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp
    type: front-end
spec:
  template:
    metadata:
      name: mynginx
      labels:
        app: nginx
        tier: frontend
    spec:
     containers:
      - name: nginx1
        image: nginx
  replicas: 3